### ISSUE TITLE
Network Upgrades?

### ISSUE THREAD

**Issue by lexzaiello** [SummerCash/go-summercash#1]
Going to be pushing a ton of system upgrades in the coming weeks before SummerTech. Would it be possible to have the aws nodes automatically upgrade every two days or so? @space55

**Comment by space55** [comment]
Affirm. I’ll have them update every day at 5 am. I figure that’s late enough for your last commit of the night to be pulled.

**Comment by lexzaiello** [comment]
Sounds good! Thanks.

**Comment by lexzaiello** [comment]
Actually, one more thing: I reset the network on my side just last night. Could you `sudo rm -rf data/db` before I add the aws nodes back into the network? @space55

**Comment by space55** [comment]
Done on both. node1 will pull at 5, node2 at 6.

Edit: I've already pulled on both, but that's the schedule for further pulls

**Comment by lexzaiello** [comment]
Perfect! Looks like the nodes are connected. Now, this shouldn't be an issue for the immediate future, but before I add the AWS nodes back into the bootstrap nodes list, could you also `sudo rm -rf data/config && sudo rm -rf data/db` and restart both nodes (forgot to mention that data/config had to be redownloaded as well)?

**Comment by lexzaiello** [comment]
Now, one more issue: on both of the nodes that I've checked, the last aws node was not able to connect to the network. Not sure if the actual instance is down, or if it's repeatedly panicking.
